import { Service } from './types';

type SeedService = Omit<Service, 'id' | 'contractor_id' | 'created_at'>;

export const DEFAULT_SERVICES: SeedService[] = [
  {
    key: 'patio',
    label: 'Patio / Interlock',
    unit: 'sq ft',
    is_slider: true,
    slider_min: 100,
    slider_max: 2000,
    slider_step: 25,
    default_qty: 400,
    display_order: 0,
    is_active: true,
    prod_rate_good_low: 150,
    prod_rate_good_high: 200,
    prod_rate_better_low: 120,
    prod_rate_better_high: 160,
    prod_rate_best_low: 80,
    prod_rate_best_high: 120,
    days_good_low: null,
    days_good_high: null,
    days_better_low: null,
    days_better_high: null,
    days_best_low: null,
    days_best_high: null,
    mat_cost_good_low: 8,
    mat_cost_good_high: 10,
    mat_cost_better_low: 12,
    mat_cost_better_high: 16,
    mat_cost_best_low: 18,
    mat_cost_best_high: 25,
  },
  {
    key: 'retaining_wall',
    label: 'Retaining Wall',
    unit: 'lin ft',
    is_slider: true,
    slider_min: 10,
    slider_max: 200,
    slider_step: 5,
    default_qty: 40,
    display_order: 1,
    is_active: true,
    prod_rate_good_low: 20,
    prod_rate_good_high: 30,
    prod_rate_better_low: 15,
    prod_rate_better_high: 22,
    prod_rate_best_low: 10,
    prod_rate_best_high: 15,
    days_good_low: null,
    days_good_high: null,
    days_better_low: null,
    days_better_high: null,
    days_best_low: null,
    days_best_high: null,
    mat_cost_good_low: 30,
    mat_cost_good_high: 45,
    mat_cost_better_low: 50,
    mat_cost_better_high: 70,
    mat_cost_best_low: 75,
    mat_cost_best_high: 100,
  },
  {
    key: 'steps',
    label: 'Steps / Stairs',
    unit: 'steps',
    is_slider: true,
    slider_min: 2,
    slider_max: 20,
    slider_step: 1,
    default_qty: 4,
    display_order: 2,
    is_active: true,
    prod_rate_good_low: 4,
    prod_rate_good_high: 6,
    prod_rate_better_low: 3,
    prod_rate_better_high: 4,
    prod_rate_best_low: 2,
    prod_rate_best_high: 3,
    days_good_low: null,
    days_good_high: null,
    days_better_low: null,
    days_better_high: null,
    days_best_low: null,
    days_best_high: null,
    mat_cost_good_low: 150,
    mat_cost_good_high: 200,
    mat_cost_better_low: 250,
    mat_cost_better_high: 350,
    mat_cost_best_low: 400,
    mat_cost_best_high: 550,
  },
  {
    key: 'driveway',
    label: 'Driveway',
    unit: 'sq ft',
    is_slider: true,
    slider_min: 200,
    slider_max: 1500,
    slider_step: 25,
    default_qty: 600,
    display_order: 3,
    is_active: true,
    prod_rate_good_low: 150,
    prod_rate_good_high: 200,
    prod_rate_better_low: 120,
    prod_rate_better_high: 160,
    prod_rate_best_low: 80,
    prod_rate_best_high: 120,
    days_good_low: null,
    days_good_high: null,
    days_better_low: null,
    days_better_high: null,
    days_best_low: null,
    days_best_high: null,
    mat_cost_good_low: 8,
    mat_cost_good_high: 10,
    mat_cost_better_low: 12,
    mat_cost_better_high: 16,
    mat_cost_best_low: 18,
    mat_cost_best_high: 25,
  },
  {
    key: 'walkway',
    label: 'Walkway / Path',
    unit: 'sq ft',
    is_slider: true,
    slider_min: 50,
    slider_max: 600,
    slider_step: 10,
    default_qty: 150,
    display_order: 4,
    is_active: true,
    prod_rate_good_low: 100,
    prod_rate_good_high: 150,
    prod_rate_better_low: 80,
    prod_rate_better_high: 120,
    prod_rate_best_low: 60,
    prod_rate_best_high: 90,
    days_good_low: null,
    days_good_high: null,
    days_better_low: null,
    days_better_high: null,
    days_best_low: null,
    days_best_high: null,
    mat_cost_good_low: 8,
    mat_cost_good_high: 10,
    mat_cost_better_low: 12,
    mat_cost_better_high: 16,
    mat_cost_best_low: 18,
    mat_cost_best_high: 25,
  },
  {
    key: 'outdoor_kitchen',
    label: 'Outdoor Kitchen',
    unit: 'project',
    is_slider: false,
    slider_min: 1,
    slider_max: 1,
    slider_step: 1,
    default_qty: 1,
    display_order: 5,
    is_active: true,
    prod_rate_good_low: null,
    prod_rate_good_high: null,
    prod_rate_better_low: null,
    prod_rate_better_high: null,
    prod_rate_best_low: null,
    prod_rate_best_high: null,
    days_good_low: 3,
    days_good_high: 4,
    days_better_low: 4,
    days_better_high: 6,
    days_best_low: 6,
    days_best_high: 8,
    mat_cost_good_low: 5000,
    mat_cost_good_high: 7000,
    mat_cost_better_low: 8000,
    mat_cost_better_high: 12000,
    mat_cost_best_low: 15000,
    mat_cost_best_high: 22000,
  },
  {
    key: 'firepit',
    label: 'Fire Pit / Fireplace',
    unit: 'project',
    is_slider: false,
    slider_min: 1,
    slider_max: 1,
    slider_step: 1,
    default_qty: 1,
    display_order: 6,
    is_active: true,
    prod_rate_good_low: null,
    prod_rate_good_high: null,
    prod_rate_better_low: null,
    prod_rate_better_high: null,
    prod_rate_best_low: null,
    prod_rate_best_high: null,
    days_good_low: 1,
    days_good_high: 1.5,
    days_better_low: 1.5,
    days_better_high: 2,
    days_best_low: 2,
    days_best_high: 3,
    mat_cost_good_low: 1500,
    mat_cost_good_high: 2500,
    mat_cost_better_low: 3000,
    mat_cost_better_high: 4500,
    mat_cost_best_low: 5000,
    mat_cost_best_high: 8000,
  },
  {
    key: 'pergola',
    label: 'Pergola / Shade Structure',
    unit: 'project',
    is_slider: false,
    slider_min: 1,
    slider_max: 1,
    slider_step: 1,
    default_qty: 1,
    display_order: 7,
    is_active: true,
    prod_rate_good_low: null,
    prod_rate_good_high: null,
    prod_rate_better_low: null,
    prod_rate_better_high: null,
    prod_rate_best_low: null,
    prod_rate_best_high: null,
    days_good_low: 2,
    days_good_high: 3,
    days_better_low: 3,
    days_better_high: 4,
    days_best_low: 4,
    days_best_high: 6,
    mat_cost_good_low: 3000,
    mat_cost_good_high: 5000,
    mat_cost_better_low: 6000,
    mat_cost_better_high: 9000,
    mat_cost_best_low: 10000,
    mat_cost_best_high: 15000,
  },
  {
    key: 'lighting',
    label: 'Landscape Lighting',
    unit: 'project',
    is_slider: false,
    slider_min: 1,
    slider_max: 1,
    slider_step: 1,
    default_qty: 1,
    display_order: 8,
    is_active: true,
    prod_rate_good_low: null,
    prod_rate_good_high: null,
    prod_rate_better_low: null,
    prod_rate_better_high: null,
    prod_rate_best_low: null,
    prod_rate_best_high: null,
    days_good_low: 0.5,
    days_good_high: 1,
    days_better_low: 1,
    days_better_high: 1.5,
    days_best_low: 1.5,
    days_best_high: 2,
    mat_cost_good_low: 1000,
    mat_cost_good_high: 2000,
    mat_cost_better_low: 2500,
    mat_cost_better_high: 4000,
    mat_cost_best_low: 4500,
    mat_cost_best_high: 7000,
  },
  {
    key: 'garden_bed',
    label: 'Garden Bed / Planting',
    unit: 'sq ft',
    is_slider: true,
    slider_min: 50,
    slider_max: 1000,
    slider_step: 25,
    default_qty: 200,
    display_order: 9,
    is_active: true,
    prod_rate_good_low: 200,
    prod_rate_good_high: 300,
    prod_rate_better_low: 150,
    prod_rate_better_high: 200,
    prod_rate_best_low: 100,
    prod_rate_best_high: 150,
    days_good_low: null,
    days_good_high: null,
    days_better_low: null,
    days_better_high: null,
    days_best_low: null,
    days_best_high: null,
    mat_cost_good_low: 5,
    mat_cost_good_high: 8,
    mat_cost_better_low: 10,
    mat_cost_better_high: 15,
    mat_cost_best_low: 16,
    mat_cost_best_high: 22,
  },
];

export const DEFAULT_PRICING_CONFIG = {
  crew_rate_per_day: 3000,
  crew_multiplier: 1.25,
  tier_good_multiplier: 1.0,
  tier_better_multiplier: 1.15,
  tier_best_multiplier: 1.35,
  tier_good_label: 'Good',
  tier_good_desc: 'Standard materials, clean & functional.',
  tier_better_label: 'Better',
  tier_better_desc: 'Upgraded materials, more design complexity.',
  tier_best_label: 'Best',
  tier_best_desc: 'Premium materials, complex design, full vision.',
  site_standard_add_days: 0,
  site_moderate_add_days: 0.5,
  site_complex_add_days: 1,
  rounding_increment: 500,
  minimum_estimate: 5000,
  show_hst: true,
  hst_rate: 0.13,
  currency: 'CAD',
};
